### ISSUE TITLE
关于 inference 数据集的掩码

### ISSUE THREAD

**Issue by wuzhiqi111** [LeipingJie/SAMShadow#3]
作者你好，我想咨询关于你的模型去推理独立数据集的问题。

比如说我这边有一个test数据集，没有gt，也没有对应的掩码。我想通过你的pipeline去生成这些图像的掩码。

我修改了yml里面的相关配置，但是依然报错显示缺少相关的txt文件，

Traceback (most recent call last):
  File "/mnt/lustre/GPU4/home/wuzhiqi/workspace/2024/SAMShadow/eval_shadow.py", line 174, in <module>
    evaluate(opt, args)
  File "/mnt/lustre/GPU4/home/wuzhiqi/workspace/2024/SAMShadow/eval_shadow.py", line 125, in evaluate
    with open(txt, 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: './preds/NTIRE/0055/fm.txt'。

所以，这些txt是你自己编写的吗，如果去推理除了你所提到的四个数据集之外是不成立的吗，望解答，谢谢。

**Comment by cvbird** [comment]
你好。因为SAM默认会生成多个预测mask，所以需要有一种方式来选择最佳的预测mask（文中是采用的F-measure或者IOU值）。也就是说会从预测的所有mask中选择最佳mask来做evaluation。因此，如果没有对应的真实掩码的话，就无法合理选择出哪一张图片作为最终的预测掩码。如果你需要推理不包含gt mask的数据集，可以参考我们一个后续的工作：https://arxiv.org/abs/2311.08891，代码也已经开源。谢谢。

**Comment by LeipingJie** [comment]
你好。因为SAM默认会生成多个预测mask，所以需要有一种方式来选择最佳的预测mask（文中是采用的F-measure或者IOU值）。也就是说会从预测的所有mask中选择最佳mask来做evaluation。因此，如果没有对应的真实掩码的话，就无法合理选择出哪一张图片作为最终的预测掩码。如果你需要推理不包含gt mask的数据集，可以参考我们一个后续的工作：[https://arxiv.org/abs/2311.08891，代码也已经开源。谢谢。](https://arxiv.org/abs/2311.08891%EF%BC%8C%E4%BB%A3%E7%A0%81%E4%B9%9F%E5%B7%B2%E7%BB%8F%E5%BC%80%E6%BA%90%E3%80%82%E8%B0%A2%E8%B0%A2%E3%80%82)
